# Generated by Django 3.2.8 on 2021-10-06 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'phonenumber',
                'verbose_name_plural': 'phonenumbers',
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('result', models.IntegerField(choices=[(0, 'pending'), (1, 'has-tg'), (2, 'no-username'), (3, 'error')], verbose_name='Result')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phonechecker.phonenumber', verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'check',
                'verbose_name_plural': 'checks',
            },
        ),
    ]
