# Generated by Django 3.2.8 on 2021-10-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='batch',
            field=models.CharField(default='dummy-uuid', max_length=80, verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='check',
            name='result',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'has-tg'), (2, 'no-username'), (3, 'error')], default=0, verbose_name='Result'),
        ),
    ]
