# Generated by Django 3.2.8 on 2021-10-07 05:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0002_auto_20211006_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100, verbose_name='Batch')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Code')),
                ('two_factor', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Two Factor')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'botlogin',
                'verbose_name_plural': 'botlogins',
            },
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number'),
        ),
    ]
