# Generated by Django 3.2.8 on 2021-10-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0004_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='batch_id',
            field=models.CharField(default='dummy', max_length=100, verbose_name='Batch Id'),
            preserve_default=False,
        ),
    ]
