# Generated by Django 3.2.8 on 2021-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0005_upload_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='batch_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Batch Id'),
        ),
    ]
