# Generated by Django 3.2.8 on 2021-10-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0006_alter_upload_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='phone_column',
            field=models.CharField(max_length=200, verbose_name='Column Name'),
        ),
    ]
