# Generated by Django 3.2.8 on 2021-10-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0007_alter_upload_phone_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botlogin',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Phone Number'),
        ),
    ]
