# Generated by Django 3.2.8 on 2021-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0008_auto_20211008_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='phone_column',
            field=models.CharField(default='PhoneNumbers', max_length=200, verbose_name='Column Name'),
        ),
    ]
