# Generated by Django 3.2.8 on 2021-10-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0009_alter_upload_phone_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='debug',
            field=models.TextField(blank=True, null=True, verbose_name='Debug'),
        ),
    ]
