# Generated by Django 3.2.8 on 2021-10-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0010_check_debug'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Username'),
        ),
    ]
