# Generated by Django 3.2.8 on 2021-10-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0012_mysql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql',
            name='db_port',
            field=models.IntegerField(default=3306, verbose_name='DB Port'),
        ),
    ]
