# Generated by Django 3.2.8 on 2021-10-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0013_alter_mysql_db_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysql',
            name='batch_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Batch Id'),
        ),
        migrations.AddField(
            model_name='mysql',
            name='db_column',
            field=models.CharField(default='dummy', max_length=100, verbose_name='DB Column Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mysql',
            name='db_table',
            field=models.CharField(default='dummy', max_length=100, verbose_name='DB Table Name'),
            preserve_default=False,
        ),
    ]
