# Generated by Django 3.2.8 on 2021-10-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0016_upload_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='source',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Source'),
        ),
    ]
