# Generated by Django 3.2.8 on 2021-10-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0019_phonenumber_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Timestamp'),
        ),
    ]
