# Generated by Django 3.2.8 on 2021-10-18 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phonechecker', '0021_alter_upload_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysql',
            name='batch_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True, verbose_name='Batch Id'),
        ),
    ]
